input = open("rosalind_dna.txt", 'r')
dna_str = input.readline()
dna_str = dna_str.upper()
count_A = dna_str.count("A")
count_C = dna_str.count("C")
count_G = dna_str.count("G")
count_T = dna_str.count("T")
print(count_A, count_C, count_G, count_T)
input.close()
